apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    run: proxy
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c']
    args: ["echo '|
      <html>
      <body bgcolor=\"black\">
      <h2><font color=\"gold\">EmptyDir</font></h2><br><p>
      <font color=\"magenta\">
      <b>Version 1.0<b>
      </body>
      </html>' > /usr/local/apache2/htdocs/index.html"]
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: html
  containers:
  - name: httpd
    image: httpd:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs
      name: html
  volumes:
  - name: html
    emptyDir:
      sizeLimit: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  selector:
    run: proxy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80