version: "3"
services:
  apache2:
    build: ./Debian-apache2
    ports:
      - 8080:80
    volumes:
      - ./Debian-apache2/html:/opt/apache2/tms.guranchik.com
      - ./Debian-apache2/logs:/opt/apache2/logs
    networks:
      - TMS_net



  nginx:
    build: ./fedora-nginx
    ports:
      - 8081:80
    volumes:
      - ./fedora-nginx/html:/opt/nginx/tms.guranchik.com
      - ./fedora-nginx/logs:/opt/nginx/logs
    networks:
      - TMS_net
  
networks:
  TMS_net:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.1/24