nodes = {
  "vm1" => ["bytesguy/debian-11-arm64", 2, 2028],
  "vm2" => ["bytesguy/ubuntu-server-20.04-arm64", 2, 2048],
  "vm3" => ["jacobw/fedora35-arm64", 2, 2048]
}

Vagrant.configure("2") do |config|
  nodes.each do | (name, cfg) |
    box, numvcpus, memory = cfg
    
    config.vm.define name do |machine|
      machine.vm.box = box
      machine.vm.hostname = name
      machine.vm.synced_folder('.', '/vagrant', type: 'rsync')
      machine.vm.provider :vmware_fusion do |fusion|
        fusion.gui = true
        fusion.vmx["displayname"] = name
        fusion.vmx["memsize"] = memory
        fusion.vmx["numvcpus"] = numvcpus
        fusion.vmx["ethernet0.connectiontype"] = "bridged"
        fusion.vmx["cpuid.coresPerSocket"] = "1"
      end
      machine.vm.provision "ubuntu", type: "shell", inline: <<-SHELL
        sudo su
        USER='ansible'
        useradd -m "$USER"
        mkdir -p /home/"$USER"/.ssh
        cat /vagrant/id_rsa.pub >> /home/"$USER"/.ssh/authorized_keys
        chown "$USER":"$USER" /home/"$USER" -R
        chmod 600 /home/"$USER"/.ssh/authorized_keys
        chmod 700 /home/"$USER"/.ssh
        echo "$USER ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
        ip a | grep -oe "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\/22"
      SHELL
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "PlaybookApache2.yml"
  end
end
